// This file was auto-generated by ML.NET Model Builder. 
namespace Regression_ExercisesML.ConsoleApp
{
    using Microsoft.ML;
    using Microsoft.ML.Trainers.FastTree;
    using Regression_ExercisesML.Model;
    using System;
    using System.Collections.Generic;
    using System.IO;

    class Program
    {
        //Machine learning model to load and use for predictions
        private const string MODEL_FILEPATH = @"C:\Users\Toni\source\repos\CarPricePrediction\CarPricePrediction\Regression.ExercisesML.ConsoleApp\MLModel.zip";

        private static string TRAIN_DATA_FILEPATH = @"C:\Users\Toni\source\repos\CarPricePrediction\CarPricePrediction\Regression.ExercisesML.ConsoleApp\carsbg.csv";


        static void Main(string[] args)
        {
            if (!File.Exists(MODEL_FILEPATH))
            {
                TrainModel();
            }

            var listOfInputs = new List<ModelInput>()
            {
                new ModelInput()
                {
                    Make = "VW",
                    Model = "Golf",
                    CubicCapacity = 1400,
                    FuelType = "Бензин",
                    Gear = "Ръчни",
                    HorsePower = 55,
                    Range = 270000,
                    Year = "01/01/1992"
                },
                new ModelInput()
                {
                    Make = "Suzuki",
                    Model = "Grand Vitara",
                    Year = "01/01/2002",
                    Range = 150000,
                    HorsePower = 109,
                    FuelType = "Дизел",
                    Gear = "Ръчни",
                    CubicCapacity = 2000
                },
                new ModelInput()
                {
                    Make = "Lamborghini",
                    Model = "Urus",
                    Year = "01/01/2019",
                    Range = 10,
                    HorsePower = 650,
                    FuelType = "Бензин",
                    Gear = "Автоматични",
                    CubicCapacity = 4000
                }
            };

            TestModel(MODEL_FILEPATH, listOfInputs);
        }

        private static void TrainModel()
        {
            MLContext mlContext = new MLContext(seed: 1);
            // Load Data
            IDataView trainingDataView = mlContext.Data.LoadFromTextFile<ModelInput>(
                                            path: TRAIN_DATA_FILEPATH,
                                            hasHeader: true,
                                            separatorChar: ',',
                                            allowQuoting: true,
                                            allowSparse: false);

            // Build training pipeline
            var dataProcessPipeline = mlContext.Transforms.Categorical.OneHotEncoding(new[]
            {
                new InputOutputColumnPair("Make", "Make"),
                new InputOutputColumnPair("FuelType", "FuelType"),
                new InputOutputColumnPair("Year", "Year"),
                new InputOutputColumnPair("Gear", "Gear") })
                                       .Append(mlContext.Transforms.Categorical.OneHotHashEncoding(new[] { new InputOutputColumnPair("Model", "Model") }))
                                       .Append(mlContext.Transforms.Concatenate("Features", new[] { "Make", "FuelType", "Year", "Gear", "Model", "HorsePower", "Range", "CubicCapacity" }));
            // Set the training algorithm 
            var trainer = mlContext.Regression.Trainers.FastTree(new FastTreeRegressionTrainer.Options()
            {
                NumberOfLeaves = 86,
                MinimumExampleCountPerLeaf = 1,
                NumberOfTrees = 500,
                LearningRate = 0.2955536f,
                Shrinkage = 0.1973613f,
                LabelColumnName = "Price",
                FeatureColumnName = "Features"
            });

            var trainingPipeline = dataProcessPipeline.Append(trainer);

            // Evaluate quality of Model

            // Train Model
            ITransformer mlModel = trainingPipeline.Fit(trainingDataView);

            // Save model
            mlContext.Model.Save(mlModel, trainingDataView.Schema, MODEL_FILEPATH);
        }

        private static void TestModel(string MODEL_FILEPATH, List<ModelInput> listOfInputs)
        {
            MLContext mLContext = new MLContext();
            var model = mLContext.Model.Load(MODEL_FILEPATH, out _);

            var predictionEngine = mLContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(model);

            foreach (var item in listOfInputs)
            {
                var prediction = predictionEngine.Predict(item);
                Console.WriteLine(new string('-', 60));
                Console.WriteLine($"Make: {item.Make}");
                Console.WriteLine($"Model: {item.Model}");
                Console.WriteLine($"Prediction: {prediction.Score}");
            }
        }
    }
}
